---
title: "西遊記文字雲"
author: "陳哲偉"
date: "2019年7月18日"
output: html_document
---
#### 目的:找西遊記中師父和徒弟的相關詞和出現最多的關鍵詞
###### 資料來源 [小說文字檔](http://www.solidfiles.com/d/a3187044a8/),[參考資料](https://zhuanlan.zhihu.com/p/33010506)

# 載入套件
```{r}
library(jiebaR)
library(jiebaRD)
library(wordcloud2)

library(text2vec)
library(stringr)

```

# 讀文檔
```{r}
setwd("C:/Users/jeff6/Desktop/Github/alan/Week2-4")
data <- readChar("CUG.txt",720000)
str(data)
```

# 斷詞工具
```{r}
cutter <- worker(stop_word = "C:/Users/jeff6/Desktop/Github/alan/Week2-4/a.txt")
new_user_word(cutter, "老孫")
```

# 斷詞、轉成list格式
```{r}
x <- segment(data,cutter)
tokens=list(x)
class(tokens)
```

# 建構詞庫（對全文分詞结果進行彙總）看前30
```{r}
it = itoken(tokens, progressbar = FALSE)
vocab = create_vocabulary(it)
vocab=vocab[which(nchar(vocab$term)>1),]#刪除一個字的詞
vocab = prune_vocabulary(vocab, term_count_min = 10L)#刪除出現小於10次的詞
tail(vocab,30)# 查看最高频的詞
vectorizer = vocab_vectorizer(vocab)
tcm = create_tcm(it, vectorizer,skip_grams_window = 10L)#考慮詞的前後10個詞




```


```{r}

```

# 設置詞向量是4维的
```{r}
glove = GlobalVectors$new(word_vectors_size = 40, vocabulary = vocab, x_max = 10)
wv_main = glove$fit_transform(tcm, n_iter = 10, convergence_tol = 0.01)
dim(wv_main)
wv_context = glove$components
dim(wv_context)
wv_main[1,1]
t(wv_context)[1,1]
word_vectors = wv_main + t(wv_context)
```

# 建構師父+徒弟向量
```{r}
relation = word_vectors["師父", , drop = FALSE] +
  word_vectors["徒弟", , drop = FALSE]
```

# **和師父、徒弟相關性前十四個詞**
```{r}
cos_sim = sim2(x = word_vectors, y = relation, method = "cosine", norm = "l2")
head(sort(cos_sim[,1], decreasing = TRUE), 14)
```

# **文字雲**
```{r}
z <- sort(table(x),decreasing = T)[1:100]#排序取前100
z <- data.frame(z)#轉成dataframe

wordcloud2(z,
           size = 2,
           backgroundColor = "black",
           color = "random-light",
           shape = "triangle")

```





